// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -destination mocks_test.go -package auth_test
//

// Package auth_test is a generated GoMock package.
package auth_test

import (
	context "context"
	reflect "reflect"

	model "git.iu7.bmstu.ru/kia22u475/ppo/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockauthRepo is a mock of authRepo interface.
type MockauthRepo struct {
	ctrl     *gomock.Controller
	recorder *MockauthRepoMockRecorder
	isgomock struct{}
}

// MockauthRepoMockRecorder is the mock recorder for MockauthRepo.
type MockauthRepoMockRecorder struct {
	mock *MockauthRepo
}

// NewMockauthRepo creates a new mock instance.
func NewMockauthRepo(ctrl *gomock.Controller) *MockauthRepo {
	mock := &MockauthRepo{ctrl: ctrl}
	mock.recorder = &MockauthRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockauthRepo) EXPECT() *MockauthRepoMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockauthRepo) CreateSession(userID int64) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", userID)
	ret0, _ := ret[0].(string)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockauthRepoMockRecorder) CreateSession(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockauthRepo)(nil).CreateSession), userID)
}

// DeleteSession mocks base method.
func (m *MockauthRepo) DeleteSession(sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockauthRepoMockRecorder) DeleteSession(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockauthRepo)(nil).DeleteSession), sessionID)
}

// GetUserIDBySessionID mocks base method.
func (m *MockauthRepo) GetUserIDBySessionID(sessionID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDBySessionID", sessionID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDBySessionID indicates an expected call of GetUserIDBySessionID.
func (mr *MockauthRepoMockRecorder) GetUserIDBySessionID(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDBySessionID", reflect.TypeOf((*MockauthRepo)(nil).GetUserIDBySessionID), sessionID)
}

// SessionExists mocks base method.
func (m *MockauthRepo) SessionExists(sessionID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionExists", sessionID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// SessionExists indicates an expected call of SessionExists.
func (mr *MockauthRepoMockRecorder) SessionExists(sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionExists", reflect.TypeOf((*MockauthRepo)(nil).SessionExists), sessionID)
}

// MockuserRepo is a mock of userRepo interface.
type MockuserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepoMockRecorder
	isgomock struct{}
}

// MockuserRepoMockRecorder is the mock recorder for MockuserRepo.
type MockuserRepoMockRecorder struct {
	mock *MockuserRepo
}

// NewMockuserRepo creates a new mock instance.
func NewMockuserRepo(ctrl *gomock.Controller) *MockuserRepo {
	mock := &MockuserRepo{ctrl: ctrl}
	mock.recorder = &MockuserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepo) EXPECT() *MockuserRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockuserRepo) Create(ctx context.Context, login, password, role string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, login, password, role)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockuserRepoMockRecorder) Create(ctx, login, password, role any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockuserRepo)(nil).Create), ctx, login, password, role)
}

// GetByLogin mocks base method.
func (m *MockuserRepo) GetByLogin(ctx context.Context, login string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByLogin", ctx, login)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByLogin indicates an expected call of GetByLogin.
func (mr *MockuserRepoMockRecorder) GetByLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByLogin", reflect.TypeOf((*MockuserRepo)(nil).GetByLogin), ctx, login)
}
