// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -destination mocks_test.go -package item_test
//

// Package item_test is a generated GoMock package.
package item_test

import (
	context "context"
	reflect "reflect"

	model "github.com/b0pof/ppo/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockitemRepo is a mock of itemRepo interface.
type MockitemRepo struct {
	ctrl     *gomock.Controller
	recorder *MockitemRepoMockRecorder
	isgomock struct{}
}

// MockitemRepoMockRecorder is the mock recorder for MockitemRepo.
type MockitemRepoMockRecorder struct {
	mock *MockitemRepo
}

// NewMockitemRepo creates a new mock instance.
func NewMockitemRepo(ctrl *gomock.Controller) *MockitemRepo {
	mock := &MockitemRepo{ctrl: ctrl}
	mock.recorder = &MockitemRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemRepo) EXPECT() *MockitemRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockitemRepo) Create(ctx context.Context, item model.Item) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, item)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockitemRepoMockRecorder) Create(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockitemRepo)(nil).Create), ctx, item)
}

// DeleteByID mocks base method.
func (m *MockitemRepo) DeleteByID(ctx context.Context, itemID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, itemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockitemRepoMockRecorder) DeleteByID(ctx, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockitemRepo)(nil).DeleteByID), ctx, itemID)
}

// GetAllItems mocks base method.
func (m *MockitemRepo) GetAllItems(ctx context.Context, userID int64) ([]model.ItemExtended, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllItems", ctx, userID)
	ret0, _ := ret[0].([]model.ItemExtended)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllItems indicates an expected call of GetAllItems.
func (mr *MockitemRepoMockRecorder) GetAllItems(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllItems", reflect.TypeOf((*MockitemRepo)(nil).GetAllItems), ctx, userID)
}

// GetByID mocks base method.
func (m *MockitemRepo) GetByID(ctx context.Context, itemID, userID int64) (model.ItemExtended, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, itemID, userID)
	ret0, _ := ret[0].(model.ItemExtended)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockitemRepoMockRecorder) GetByID(ctx, itemID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockitemRepo)(nil).GetByID), ctx, itemID, userID)
}

// GetItemsByOrderID mocks base method.
func (m *MockitemRepo) GetItemsByOrderID(ctx context.Context, orderID int64) ([]model.OrderItemInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemsByOrderID", ctx, orderID)
	ret0, _ := ret[0].([]model.OrderItemInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemsByOrderID indicates an expected call of GetItemsByOrderID.
func (mr *MockitemRepoMockRecorder) GetItemsByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemsByOrderID", reflect.TypeOf((*MockitemRepo)(nil).GetItemsByOrderID), ctx, orderID)
}

// GetItemsBySellerID mocks base method.
func (m *MockitemRepo) GetItemsBySellerID(ctx context.Context, sellerID int64) ([]model.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemsBySellerID", ctx, sellerID)
	ret0, _ := ret[0].([]model.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemsBySellerID indicates an expected call of GetItemsBySellerID.
func (mr *MockitemRepoMockRecorder) GetItemsBySellerID(ctx, sellerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemsBySellerID", reflect.TypeOf((*MockitemRepo)(nil).GetItemsBySellerID), ctx, sellerID)
}

// UpdateByID mocks base method.
func (m *MockitemRepo) UpdateByID(ctx context.Context, item model.Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockitemRepoMockRecorder) UpdateByID(ctx, item any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockitemRepo)(nil).UpdateByID), ctx, item)
}
