// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -destination mocks_test.go -package order_test
//

// Package order_test is a generated GoMock package.
package order_test

import (
	context "context"
	reflect "reflect"

	model "github.com/b0pof/ppo/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockorderRepo is a mock of orderRepo interface.
type MockorderRepo struct {
	ctrl     *gomock.Controller
	recorder *MockorderRepoMockRecorder
	isgomock struct{}
}

// MockorderRepoMockRecorder is the mock recorder for MockorderRepo.
type MockorderRepoMockRecorder struct {
	mock *MockorderRepo
}

// NewMockorderRepo creates a new mock instance.
func NewMockorderRepo(ctrl *gomock.Controller) *MockorderRepo {
	mock := &MockorderRepo{ctrl: ctrl}
	mock.recorder = &MockorderRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockorderRepo) EXPECT() *MockorderRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockorderRepo) Create(ctx context.Context, userID int64, items []model.CartItem) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, items)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockorderRepoMockRecorder) Create(ctx, userID, items any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockorderRepo)(nil).Create), ctx, userID, items)
}

// GetByID mocks base method.
func (m *MockorderRepo) GetByID(ctx context.Context, orderID int64) (model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, orderID)
	ret0, _ := ret[0].(model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockorderRepoMockRecorder) GetByID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockorderRepo)(nil).GetByID), ctx, orderID)
}

// GetOrdersByUserID mocks base method.
func (m *MockorderRepo) GetOrdersByUserID(ctx context.Context, userID int64) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUserID", ctx, userID)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByUserID indicates an expected call of GetOrdersByUserID.
func (mr *MockorderRepoMockRecorder) GetOrdersByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUserID", reflect.TypeOf((*MockorderRepo)(nil).GetOrdersByUserID), ctx, userID)
}

// UpdateStatus mocks base method.
func (m *MockorderRepo) UpdateStatus(ctx context.Context, orderID int64, newStatus string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, orderID, newStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockorderRepoMockRecorder) UpdateStatus(ctx, orderID, newStatus any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockorderRepo)(nil).UpdateStatus), ctx, orderID, newStatus)
}

// MockitemRepo is a mock of itemRepo interface.
type MockitemRepo struct {
	ctrl     *gomock.Controller
	recorder *MockitemRepoMockRecorder
	isgomock struct{}
}

// MockitemRepoMockRecorder is the mock recorder for MockitemRepo.
type MockitemRepoMockRecorder struct {
	mock *MockitemRepo
}

// NewMockitemRepo creates a new mock instance.
func NewMockitemRepo(ctrl *gomock.Controller) *MockitemRepo {
	mock := &MockitemRepo{ctrl: ctrl}
	mock.recorder = &MockitemRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemRepo) EXPECT() *MockitemRepoMockRecorder {
	return m.recorder
}

// GetItemsByOrderID mocks base method.
func (m *MockitemRepo) GetItemsByOrderID(ctx context.Context, orderID int64) ([]model.OrderItemInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItemsByOrderID", ctx, orderID)
	ret0, _ := ret[0].([]model.OrderItemInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItemsByOrderID indicates an expected call of GetItemsByOrderID.
func (mr *MockitemRepoMockRecorder) GetItemsByOrderID(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItemsByOrderID", reflect.TypeOf((*MockitemRepo)(nil).GetItemsByOrderID), ctx, orderID)
}

// MockcartRepo is a mock of cartRepo interface.
type MockcartRepo struct {
	ctrl     *gomock.Controller
	recorder *MockcartRepoMockRecorder
	isgomock struct{}
}

// MockcartRepoMockRecorder is the mock recorder for MockcartRepo.
type MockcartRepoMockRecorder struct {
	mock *MockcartRepo
}

// NewMockcartRepo creates a new mock instance.
func NewMockcartRepo(ctrl *gomock.Controller) *MockcartRepo {
	mock := &MockcartRepo{ctrl: ctrl}
	mock.recorder = &MockcartRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcartRepo) EXPECT() *MockcartRepoMockRecorder {
	return m.recorder
}

// DeleteAllCartItems mocks base method.
func (m *MockcartRepo) DeleteAllCartItems(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllCartItems", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllCartItems indicates an expected call of DeleteAllCartItems.
func (mr *MockcartRepoMockRecorder) DeleteAllCartItems(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllCartItems", reflect.TypeOf((*MockcartRepo)(nil).DeleteAllCartItems), ctx, userID)
}

// GetCartContentByUserID mocks base method.
func (m *MockcartRepo) GetCartContentByUserID(ctx context.Context, userID int64) (model.CartContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartContentByUserID", ctx, userID)
	ret0, _ := ret[0].(model.CartContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartContentByUserID indicates an expected call of GetCartContentByUserID.
func (mr *MockcartRepoMockRecorder) GetCartContentByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartContentByUserID", reflect.TypeOf((*MockcartRepo)(nil).GetCartContentByUserID), ctx, userID)
}
