// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -destination mocks_test.go -package cart_test
//

// Package cart_test is a generated GoMock package.
package cart_test

import (
	context "context"
	reflect "reflect"

	model "github.com/b0pof/ppo/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockcartRepo is a mock of cartRepo interface.
type MockcartRepo struct {
	ctrl     *gomock.Controller
	recorder *MockcartRepoMockRecorder
	isgomock struct{}
}

// MockcartRepoMockRecorder is the mock recorder for MockcartRepo.
type MockcartRepoMockRecorder struct {
	mock *MockcartRepo
}

// NewMockcartRepo creates a new mock instance.
func NewMockcartRepo(ctrl *gomock.Controller) *MockcartRepo {
	mock := &MockcartRepo{ctrl: ctrl}
	mock.recorder = &MockcartRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcartRepo) EXPECT() *MockcartRepoMockRecorder {
	return m.recorder
}

// AddItemToCart mocks base method.
func (m *MockcartRepo) AddItemToCart(ctx context.Context, userID, itemID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddItemToCart", ctx, userID, itemID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddItemToCart indicates an expected call of AddItemToCart.
func (mr *MockcartRepoMockRecorder) AddItemToCart(ctx, userID, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddItemToCart", reflect.TypeOf((*MockcartRepo)(nil).AddItemToCart), ctx, userID, itemID)
}

// DeleteAllCartItems mocks base method.
func (m *MockcartRepo) DeleteAllCartItems(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllCartItems", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllCartItems indicates an expected call of DeleteAllCartItems.
func (mr *MockcartRepoMockRecorder) DeleteAllCartItems(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllCartItems", reflect.TypeOf((*MockcartRepo)(nil).DeleteAllCartItems), ctx, userID)
}

// DeleteCartItem mocks base method.
func (m *MockcartRepo) DeleteCartItem(ctx context.Context, userID, itemID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCartItem", ctx, userID, itemID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteCartItem indicates an expected call of DeleteCartItem.
func (mr *MockcartRepoMockRecorder) DeleteCartItem(ctx, userID, itemID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCartItem", reflect.TypeOf((*MockcartRepo)(nil).DeleteCartItem), ctx, userID, itemID)
}

// GetCartContentByUserID mocks base method.
func (m *MockcartRepo) GetCartContentByUserID(ctx context.Context, userID int64) (model.CartContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartContentByUserID", ctx, userID)
	ret0, _ := ret[0].(model.CartContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartContentByUserID indicates an expected call of GetCartContentByUserID.
func (mr *MockcartRepoMockRecorder) GetCartContentByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartContentByUserID", reflect.TypeOf((*MockcartRepo)(nil).GetCartContentByUserID), ctx, userID)
}

// GetCartItemsAmount mocks base method.
func (m *MockcartRepo) GetCartItemsAmount(ctx context.Context, userID int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCartItemsAmount", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCartItemsAmount indicates an expected call of GetCartItemsAmount.
func (mr *MockcartRepoMockRecorder) GetCartItemsAmount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCartItemsAmount", reflect.TypeOf((*MockcartRepo)(nil).GetCartItemsAmount), ctx, userID)
}
