// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source contract.go -destination mocks_test.go -package user_test
//

// Package user_test is a generated GoMock package.
package user_test

import (
	context "context"
	reflect "reflect"

	model "git.iu7.bmstu.ru/kia22u475/ppo/internal/model"
	gomock "github.com/golang/mock/gomock"
)

// MockuserRepo is a mock of userRepo interface.
type MockuserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepoMockRecorder
	isgomock struct{}
}

// MockuserRepoMockRecorder is the mock recorder for MockuserRepo.
type MockuserRepoMockRecorder struct {
	mock *MockuserRepo
}

// NewMockuserRepo creates a new mock instance.
func NewMockuserRepo(ctrl *gomock.Controller) *MockuserRepo {
	mock := &MockuserRepo{ctrl: ctrl}
	mock.recorder = &MockuserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepo) EXPECT() *MockuserRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockuserRepo) Create(ctx context.Context, login, password string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, login, password)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockuserRepoMockRecorder) Create(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockuserRepo)(nil).Create), ctx, login, password)
}

// GetByID mocks base method.
func (m *MockuserRepo) GetByID(ctx context.Context, userID int64) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockuserRepoMockRecorder) GetByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockuserRepo)(nil).GetByID), ctx, userID)
}

// GetRoleByID mocks base method.
func (m *MockuserRepo) GetRoleByID(ctx context.Context, userID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByID", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByID indicates an expected call of GetRoleByID.
func (mr *MockuserRepoMockRecorder) GetRoleByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByID", reflect.TypeOf((*MockuserRepo)(nil).GetRoleByID), ctx, userID)
}

// GetUserLoginByID mocks base method.
func (m *MockuserRepo) GetUserLoginByID(ctx context.Context, userID int64) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserLoginByID", ctx, userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserLoginByID indicates an expected call of GetUserLoginByID.
func (mr *MockuserRepoMockRecorder) GetUserLoginByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserLoginByID", reflect.TypeOf((*MockuserRepo)(nil).GetUserLoginByID), ctx, userID)
}

// GetUserMetaByID mocks base method.
func (m *MockuserRepo) GetUserMetaByID(ctx context.Context, userID int64) (model.UserMetaInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserMetaByID", ctx, userID)
	ret0, _ := ret[0].(model.UserMetaInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserMetaByID indicates an expected call of GetUserMetaByID.
func (mr *MockuserRepoMockRecorder) GetUserMetaByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserMetaByID", reflect.TypeOf((*MockuserRepo)(nil).GetUserMetaByID), ctx, userID)
}

// UpdateByID mocks base method.
func (m *MockuserRepo) UpdateByID(ctx context.Context, userID int64, user model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, userID, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockuserRepoMockRecorder) UpdateByID(ctx, userID, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockuserRepo)(nil).UpdateByID), ctx, userID, user)
}

// UpdatePasswordByID mocks base method.
func (m *MockuserRepo) UpdatePasswordByID(ctx context.Context, userID int64, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePasswordByID", ctx, userID, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePasswordByID indicates an expected call of UpdatePasswordByID.
func (mr *MockuserRepoMockRecorder) UpdatePasswordByID(ctx, userID, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePasswordByID", reflect.TypeOf((*MockuserRepo)(nil).UpdatePasswordByID), ctx, userID, newPassword)
}
