name: Run Go Tests with Allure

on:
  push:
    branches:
      - main

jobs:
  e2e-tests-2fa:
    name: E2E Tests - 2FA
    runs-on: ubuntu-latest
    env:
      GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
          cache: true
          cache-dependency-path: go.sum

      - name: Install golurectl
        run: go install github.com/robotomize/go-allure/cmd/golurectl@latest

      - name: Run E2E Tests
        run: |
          make e2e-test-2fa

  e2e-tests-llm-mock:
    name: E2E Tests - Интеграция (mock)
    runs-on: ubuntu-latest
#    needs: e2e-tests-2fa
    env:
      GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
          cache: true
          cache-dependency-path: go.sum

      - name: Install golurectl
        run: go install github.com/robotomize/go-allure/cmd/golurectl@latest

      - name: Run E2E Tests
        run: |
          make e2e-test-llm-mock

  e2e-tests-llm:
    name: E2E Tests - Интеграция
    runs-on: ubuntu-latest
#    needs: e2e-tests-llm-mock
    env:
      GMAIL_ADDRESS: ${{ secrets.GMAIL_ADDRESS }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.25
          cache: true
          cache-dependency-path: go.sum

      - name: Install golurectl
        run: go install github.com/robotomize/go-allure/cmd/golurectl@latest

      - name: Run E2E Tests
        run: |
          make e2e-test-llm